#ifndef SPATIAL_SCENE_PARAMS_H_
#define SPATIAL_SCENE_PARAMS_H_

#define BUFFER_SIZE 1536    // BUFFER SIZE
#define NUM_CHANNELS 1      // NUMBER OF CHANNELS IN AUDIO STREAMS
#define NUM_STREAMS 20      // MAXIMUM NUMBER OF AUDIO STREAMS
#define NUM_SPEAKERS 8      // NUMBER OF VIRTUAL SPEAKERS
#define NUM_HRTFS 7         // NUMBER OF SELECTABLE HRTF SETS

#endif /* SPATIAL_SCENE_PARAMS_H_ */
