/*
 *  Created on: 31 January, 2019
 *      Author: Rishi Shukla
 */

#ifndef SPATIAL_SCENE_PARAMS_H_
#define SPATIAL_SCENE_PARAMS_H_

#define BUFFER_SIZE 2048   // BUFFER SIZE
#define NUM_CHANNELS 1      // NUMBER OF CHANNELS IN AUDIO STREAMS
#define NUM_STREAMS 12      // MAXIMUM NUMBER OF AUDIO STREAMS
#define NUM_SPEAKERS 8      // NUMBER OF VIRTUAL SPEAKERS
#define NUM_HRTFS 9         // NUMBER OF SELECTABLE HRTF SETS

#endif /* SPATIAL_SCENE_PARAMS_H_ */
